### ISSUE TITLE
Consider removing PowerMock

### ISSUE THREAD

**Issue by rantoniuk** [jenkinsci/jira-plugin#389]
PowerMock was removed from [plugin-pom](https://github.com/jenkinsci/plugin-pom/pull/442#issue-1002043253) due to supposed lack of activity (see #388). 
Consider pros and cons of removing it from current tests.

**Comment by artkoshelev** [comment]
I'm all in to replace existing usages with Mockito and use 1 mocking framework instead of 2

**Comment by rantoniuk** [comment]
@artkoshelev would you want to devote some time on this? :-)

**Comment by artkoshelev** [comment]
maybe =)
