### ISSUE TITLE
Variables inside JQL does not get expanded

### ISSUE THREAD

**Issue by seqizz** [jenkinsci/jira-plugin#402]
First of all, thanks for the plugin.

I expected we can use variables (at least for a while, due to https://github.com/jenkinsci/jira-plugin/pull/319). But that doesn't seem to be the case currently, at least for the specific option I've used.

- [x] Jenkins version : 2.324

- [x] Plugin version: 3.6

- [x] OS: Debian buster

### Reproduction steps

- Create a properties file
- Use this properties file to send the issue key as env variable on "**_Jira: Issue custom field updater_**"

### Results

Expected result:

Variable name to get replaced

Actual result:

Exception thrown:
```
java[30719]: 2022-01-14 14:15:31.926+0000 [id=114]        WARNING        h.plugins.jira.JiraRestService#getIssuesFromJqlSearch: Jira REST client get issue from jql search error. cause: RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[Error in the JQL Query: The character '$' is a reserved JQL character. You must enclose it in a string or use the escape '\u0024' instead. (line 1, character 9)]}]}
```

Screenshot of the configuration:

![image](https://user-images.githubusercontent.com/307899/149537534-603c4427-ffb1-46f8-bef5-64e1cbdafb51.png)

**Comment by MauBoy** [comment]
Hello! We also have this issue. Is there any update on this?

**Comment by seqizz** [comment]
Closing since the plugin is replaced. Sorry for the noise :peace_symbol:
