### ISSUE TITLE
Be able to use build/environment parameters in jql selector

### ISSUE THREAD

**Issue by mrvcmrvc** [jenkinsci/jira-plugin#460]
### Feature Request

Plugin Version => 3.7

When using **Jira: Update relevant issues** or **Jira: Issue custom field updater**, they are not able to read build parameters in **JQL selector** and in **explicit selector**.

What I am trying to do is, instead if writing **key = "EXAMPLE-1"**, I want to be able to write **key = ${IssueId}** which IssueId is a parameter defined in the job.

- Since $ is preserved for Jira, I tried to use escape character as well (**key = \\${IssueId} or key = \\\\${IssueId}**)
- I thought maybe the issue is related with missing quotation marks so I tried **key = "${IssueId}"** or **key = "\\${IssueId}"**
- I tried to add quotation marks in the build parameter (IssueId) instead of jql query (eg. if the issue id is TEST-123, then the parameter on the job is "TEST-123")

None of them worked. If I wrote a hardcoded issue id instead of a build parameter, it works flawlessly.

---

I noticed a similar feature is requested for **IssueFieldUpdateStep** to be able to use build/environment variables in field value when updating a custom field in JIRA with a given value. It has been implemented with the release of [3.2](https://github.com/jenkinsci/jira-plugin/releases/tag/jira-3.2), and here is the [commit message](https://github.com/jenkinsci/jira-plugin/pull/319/commits/12dd7e81cb2e05886b4a5bc96aacf5eb345df4e4#diff-022e48912309f7bc4e6ed655687f0cc1ee3754508cc48cdb646346018dc9a6f7) that contains the change.

---

I also checked the test code for **JqlIssueSelector**;

- It creates a jql selector with a jql containing hardcoded issue id,
![Screenshot 2022-07-25 at 21 48 56](https://user-images.githubusercontent.com/11190664/180871674-de58f463-7cba-4af3-8539-8bf7a9434da9.png)
- Selector sends the jql to session in findIssueIds() method,
![Screenshot 2022-07-25 at 21 51 14](https://user-images.githubusercontent.com/11190664/180871854-1a9ff683-90d0-49ad-ad34-d4976d250ad7.png)
- Session passes it to JiraRestService,
- JiraRestService searches issues by passing jql to JiraRestClient
![Screenshot 2022-07-25 at 21 52 25](https://user-images.githubusercontent.com/11190664/180872015-bd7e2bf5-862b-4402-bb46-9a8af4fe3415.png)

So, it looks like we need to expand the sql to envVars before sending it to JiraRestClient through JiraRestService.

---

I also found out that same or similar feature is requested in Jenkins Jira page, here are those issues;

- [JENKINS-65899](https://issues.jenkins.io/browse/JENKINS-65899?jql=resolution%20is%20EMPTY%20and%20component%3D15515)
- [JENKINS-67971](https://issues.jenkins.io/browse/JENKINS-67971?jql=resolution%20is%20EMPTY%20and%20component%3D15515)

**Comment by rantoniuk** [comment]
Hi @mrvcmrvc,

Very good analysis and as you pointed out, this was just not implemented fully in all the steps. Maybe that logic could be extracted and use across all the steps (some refactoring love ;) )

Would you have sime time to spend and contribute a Pull Request with a fix? Alternatively, please consider sponsoring one of the maintainers to spend some time on this :-)

**Comment by mrvcmrvc** [comment]
Hey @rantoniuk 

Thank you for the response. I agree, extracting the functionality and referencing it from all the required steps would be the cleanest solution.

Since I am kind of urgently in need of it, I will work on it and create a PR for the repository as soon as possible 👍
