### ISSUE TITLE
Option to use a Authorization: Bearer instead of Basic

### ISSUE THREAD

**Issue by hakamairi** [jenkinsci/jira-plugin#497]
### What feature do you want to see added?

Hi,
It would be great to be able to use Personal Access Token for all the communication with Jira.
On the self hosted instance I use there's no Basic Auth allowed, but there's an option to use Personal Access Token with `-H "Authorization: Bearer %token%"`
It would be great if the plugin supported it as an option from configuration page.

**Comment by ianpascoe19** [comment]
I agree this would be extremely nice to have for higher security jira instances

**Comment by faminepq** [comment]
I'd like to have it there as well.

**Comment by EliaBracciSumo** [comment]
Hi! I implemented that 👍  If you want you can see the implementation [here](https://github.com/jenkinsci/jira-plugin/pull/521)

**Comment by rantoniuk** [comment]
Released in [3.10](https://github.com/jenkinsci/jira-plugin/releases/tag/jira-3.10)
